# Don't print a new line at the start of the prompt
add_newline = false

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[directory]
truncation_length = 8
truncation_symbol = " â€¦/"

[git_branch]
symbol = "ï˜ "
truncation_length = 20
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_status]
conflicted = "ğŸ³  "
ahead = "ï‡™ "
behind = "ïŸ"
diverged = "ï²… "
untracked = "ïŸ•"
stashed = "ï£– "
modified = " ï­ "
staged = 'ï’‡ [++\($count\)](green)'
renamed = "ï¨£"
deleted = "ğŸ—‘"

[memory_usage]
disabled = true
threshold = -1
style = "bold dimmed green"

[username]
style_user = "green bold"
style_root = "black bold"
format = "ïŒ› [$user]($style)"
disabled = false
show_always = true
