# Don't print a new line at the start of the prompt
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 100

command_timeout = 1000

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[directory]
truncation_length = 2
truncation_symbol = " â€¦/"
read_only = " |î²• "

[git_branch]
symbol = "ï„“ "
truncation_length = 20
truncation_symbol = "â€¦"

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_status]
conflicted = "ï‡¢ "
ahead = "ï‡˜ "
behind = "î·¢ "
diverged = "î¹¨ "
untracked = "î¯Œ "
stashed = "î¸‚ "
modified = "î«´ "
staged = 'ïŠ‘ [++\($count\)](green)'
renamed = "î«° "
deleted = "îª² "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[package]
format = "via [ğŸ $version](208 bold) "

[memory_usage]
disabled = false
threshold = -1
symbol = ""
style = "purple"
format = "[${ram}]($style) "

[username]
style_user = "green bold"
style_root = "black bold"
format = "[$user]($style) "
# format = "î¤ î¼ª [$user]($style) "
disabled = false
show_always = true

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[[battery.display]]  # "bold green" style when capacity is between 30% and 95%
threshold = 95
style = "bold green"

[character]
success_symbol = "[î¼¬ ](bold green)"
error_symbol = "[îº… ](bold red)"

[python]
symbol = "îºƒ "
python_binary = "python3"
